## NORMALIZATION PROBLEM: 

Normalization is one of the most basic preprocessing techniques in
data analytics. This involves centering and scaling process. Centering means subtracting the data from the
mean and scaling means dividing with its standard deviation.

In [1]:
# Import numpy library
import numpy as np

# np.random.rand(5,5) generates random numbers between 0 and 1
X = np.random.rand(5, 5)

# .mean() computes the average of all elements
mean_X = X.mean()

# .std() computes how spread out the values are
std_X = X.std()

# Normalize X using the formula Z = (X - mean) / std
X_normalized = (X - mean_X) / std_X

# .npy is a file format used by NumPy to save arrays
np.save("X_normalized.npy", X_normalized)


print("Original Array :\n", X)
print("\nMean of X:", mean_X)
print("Standard Deviation of X:", std_X)
print("\nNormalized Array:\n", X_normalized)
print("\nNormalized array saved as 'X_normalized.npy'")

Original Array :
 [[0.21122186 0.07415366 0.14214556 0.96231907 0.47033538]
 [0.10870159 0.64421553 0.60967158 0.59935145 0.30845438]
 [0.53976583 0.48895139 0.29327916 0.16533702 0.28990805]
 [0.46078334 0.30712577 0.41112324 0.37313899 0.84664304]
 [0.645597   0.44136869 0.1261998  0.73405565 0.42044378]]

Mean of X: 0.4269716327993073
Standard Deviation of X: 0.22939313997586885

Normalized Array:
 [[-0.94052409 -1.53804938 -1.24165034  2.33375523  0.18903681]
 [-1.38744358  0.94703748  0.79644906  0.75146019 -0.51665563]
 [ 0.49170694  0.2701901  -0.58280937 -1.14055117 -0.59750516]
 [ 0.14739632 -0.52244744 -0.06908837 -0.23467417  1.82948544]
 [ 0.95305974  0.0627615  -1.31116313  1.33868003 -0.02845704]]

Normalized array saved as 'X_normalized.npy'


## DIVISIBLE BY 3 PROBLEM: 

Create the following 10 x 10 ndarray which are the squares of the first 100 positive integers From this ndarray, determine all the elements that are divisible by 3. Save the result as div_by_3.np



In [5]:
import numpy as np

# Create an array of numbers from 1 to 100
numbers = np.arange(1, 101)

# Square each number (these are the squares of the first 100 positive integers)
squares = numbers ** 2

# Reshape into a 10x10 matrix (ndarray)
A = squares.reshape(10, 10)
print("Matrix A (10x10 with squares): \n ")
print(A)

# Find all elements divisible by 3 using modulo operator
div3 = A[A % 3 == 0]
print("\n Numbers divisible by 3: \n")
print(divisible_by_3)

# Save the result into a .npy file
np.save("div_by_3.npy", div3)

print ('\nOutput Saved as div_by_3.npy')

Matrix A (10x10 with squares): 
 
[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

 Numbers divisible by 3: 

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]

Output Saved as div_by_3.npy
